// document.addEventListener('DOMContentLoaded', function() {
// 	const header = document.createElement('header');
// 	const nav = document.createElement('nav');
// 	const logo = document.createElement('div');
// 	logo.classList.add('logo');
// 	logo.className = "logo";
// 	const logoImg = document.createElement('img');
// 	logoImg.src = "../assets/favicon/apple-touch-icon.png";
// 	logoImg.alt = "Lènoir Lane logo";
// 	logo.appendChild(logoImg);
// 	const logoText = document.createElement('span');
// 	logoText.textContent = 'Lènoir Lane';
// 	logo.appendChild(logoText);
// 	nav.appendChild(logo);
// 	logo.src = "../assets/favicon/apple-touch-icon.png";
// 	nav.appendChild(logo);

// 	const ul = document.createElement('ul');
// 	const li = document.createElement('li');
// 	const home = document.createElement('a');
// 	home.href = '/index.html';
// 	home.textContent = 'Home';
// 	const about = document.createElement('a');
// 	about.href = '/about.html';
// 	about.textContent = 'About';
// 	const contact = document.createElement('a');
// 	contact.href = '/contact.html';
// 	contact.textContent = 'Contact';
// 	const login = document.createElement('a');
// 	login.href = 'pages/login.html';
// 	login.textContent = 'Log In';
// 	const signup = document.createElement('a');
// 	signup.href = 'pages/signup.html';
// 	signup.textContent = 'Sign Up';
// 	li.appendChild(home);
// 	li.appendChild(about);
// 	li.appendChild(contact);
// 	li.appendChild(login);
// 	li.appendChild(signup);
// 	ul.appendChild(li);
// 	nav.appendChild(ul);
// 	header.appendChild(nav);

// 	document.body.prepend(header);
// });
